### ISSUE TITLE
Multi Line log

### ISSUE THREAD

**Issue by abani1986** [Kittyfisto/Tailviewer#185] opened 2019-05-21 10:02 UTC
Tail viewer not detecting multi line log files.

**Comment by Kittyfisto** [comment] 2019-05-23 09:31
Sorry for taking so long, I've been busier than expected in the last few weeks. I haven't forgotten about this and I've started working on a fix yesterday evening. You can expect a fix and a new release on the beginning of next week ;)


This is a duplicate of https://github.com/Kittyfisto/Tailviewer/issues/183.

**Comment by Kittyfisto** [comment] 2019-05-28 23:53
@abani1986 Please let me know if this is fixed for you with [v0.8](https://github.com/Kittyfisto/Tailviewer/releases/tag/v0.8.0)

**Closed by Kittyfisto** 2019-05-28 23:53 UTC
Labels: duplicate
